name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - erlang: "23.3.1"
            elixir: "1.11.4"
          - erlang: "23.0"
            elixir: "1.11.2"
            lint: true
            coverage: true
          - erlang: "23.0"
            elixir: "1.10.3"
          - erlang: "22.3"
            elixir: "1.9.4"
          - erlang: "21.3"
            elixir: "1.8.2"
          - erlang: "20.3.1"
            elixir: "1.7.4"
          - erlang: "19.3"
            elixir: "1.6.6"
          - erlang: "18.3"
            elixir: "1.5.3"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.erlang}}
          elixir-version: ${{matrix.elixir}}

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-otp${{ matrix.erlang }}-elixir${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}

      - name: Install and compile dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          mix deps.get --only test
          mix deps.compile

      - name: Start docker
        run: docker-compose up --detach

      - name: Check for unused dependencies
        run: mix deps.unlock --check-unused
        if: ${{matrix.lint && steps.cache-deps.outputs.cache-hit != 'true'}}

      - name: Compile with --warnings-as-errors
        run: mix compile --warnings-as-errors
        if: ${{matrix.lint}}

      - name: Check mix format
        run: mix format --check-formatted
        if: ${{matrix.lint}}

      - name: Run tests
        run: mix test --trace --include proxy
        if: ${{ !matrix.coverage }}

      - name: Run tests with coverage
        run: mix coveralls.github --include proxy
        if: ${{ matrix.coverage }}
